### ISSUE TITLE
Squirrel Crash

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/Bunnymark-TIC80#6]
@masternama-8000

> Squirrel script version crashes a cart. I can't load code script

You're on the latest TIC? Maybe we need a new release out.

**Comment by RobLoach** [comment]
Probably crashes because this needs the latest TIC master right now.

**Comment by Masternama-8000** [comment]
@RobLoach This **0.70.6** version is not work run squirrel script it's invaild script. **0.80.0-dev** version is working fine squirrel there is no errors & invaild script.
